before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10

env:
  global:
    - TEST_ES_SERVER=http://localhost:9250
    - ELASTICSEARCH_VERSION=7.6.0
    - ENV['RAILS_ENV'] = 'test'

before_install:
  - ls $PWD
  - pkill -9 -f elasticsearch || true
  - gem --version
  - gem update bundler -q
  - bundle version
  - bundle install
  - bundle exec rake setup
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.6.0-amd64.deb && sudo service elasticsearch restart

install:
  - rake bundle:clean
  - rake bundle:install

  services:
  - postgresql
  - elasticsearch
