env:
  global:
    - TEST_ES_SERVER=http://localhost:9250
    - ELASTICSEARCH_VERSION=7.6.0
    - ENV['RAILS_ENV'] = 'test'

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10

before_install:
  - bundle version

install:
  - rake bundle:clean
  - rake bundle:install

services:
  - postgresql
  - elasticsearch
