env:
  global:
    - TEST_ES_SERVER=http://localhost:9250
    - ELASTICSEARCH_VERSION=7.6.0
    - ENV['RAILS_ENV'] = 'test'

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10

before_install:
  - gem --version
  - gem update bundler -q
  - bundle version
  - bundle install
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.6.0-amd64.deb && sudo service elasticsearch restart

install:
  - rake bundle:clean
  - rake bundle:install

services:
  - postgresql
