before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.7.deb && sudo dpkg -i --force-confnew elasticsearch-6.8.7.deb && sudo service elasticsearch restart
services:
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sleep 10
env:
  - ENV['RAILS_ENV'] = 'test'
